language: c

addons:
  apt:
    packages:
      - graphviz

# Blacklist
branches:
  except:
    - gh-pages

env:
  global:
     - PRETTYNAME="WireWrapper: Arduino Wrapper for Wire librarry (for SAM, ESP8266...)"
     - GH_REPO_NAME: WireWrapper
     - GH_REPO_REF: github.com/SMFSW/WireWrapper.git
     - DOXYFILE: $TRAVIS_BUILD_DIR/Doxyfile.auto

before_install:
   - source <(curl -SLs https://raw.githubusercontent.com/SMFSW/travis-ci-arduino/master/install.sh)

script:
   - build_main_platforms

# Generate and deploy documentation
after_success:
  - source <(curl -SLs  https://raw.githubusercontent.com/SMFSW/travis-ci-arduino/master/library_check.sh)
  - source <(curl -SLs  https://raw.githubusercontent.com/SMFSW/travis-ci-arduino/master/doxy_gen_and_deploy.sh)
